language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install --dev --no-interaction
  - mkdir -p build/logs

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v
