language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer require satooshi/php-coveralls:~0.6@stable

before_script:
  - mkdir -p build/logs

script:
  - phpunit -c phpunit.xml.dist

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
